#!/usr/bin/env python

import optparse

from ccx2.main import Ccx2

p = optparse.OptionParser(usage='usage: %prog [options]',
                          description='%prog is a console client for the xmms2 music server',
                          prog='ccx2')

p.add_option('-c', '--config',
             dest='config',
             metavar='<configpath>',
             help='path to an alternate config file',
             default=None)

opts, args = p.parse_args()

Ccx2(config_path=opts.config).main()

